#!/usr/bin/env bash

script_path="$HOME/.config/sway/menu"

# dmenu theming
. $HOME/.config/sway/menu/wmenu-theming

prompt="-p Menus:"

# list only executable non-binay files

run_dmenu="$(find $script_path/wmenu-* -maxdepth 1 -type f -executable \
          -exec grep -Iq . {} \; -print \
          | sed 's|^'$script_path/'||' \
          | sort \
          | wmenu $prompt $lines)"

eval "$script_path/$run_dmenu"

exit 0
