#!/bin/bash

selected="$(nmcli connection show | tail -n +2 | \
            wmenu -l 15 -i -p "Select network to connect to" | \
            awk '{print $1}')"; 

if [[ ! -z $selected ]]; then
    nmcli connection up $selected
fi
